import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { ThemeProvider } from "@/components/theme-provider";
import { ThemeToggle } from "@/components/theme-toggle";
import { Container, Section } from "@/components/craft";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}

const Footer = () => {
  return (
    <footer>
      <Container className="flex items-center justify-between gap-3">
        <p className="text-xs text-muted-foreground">
          Created at{" "}
          <a
            className="underline transition-all hover:text-foreground"
            href="https://wip-design.com"
          >
            WIP
          </a>{" "}
          by{" "}
          <a
            className="underline transition-all hover:text-foreground"
            href="https://bridger.to"
          >
            Bridger
          </a>
          .
        </p>
        <ThemeToggle />
      </Container>
    </footer>
  );
};
